# Generated by Django 3.2.6 on 2022-01-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0005_post_reporting_users'),
        ('lecture', '0009_alter_point_user'),
        ('comment', '0003_remove_comment_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_email', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '게시판 성격에 부적절함'), (1, '욕설/비하'), (2, '음란물/불건전한 만남 및 대화'), (3, '상업적 광고 및 판매'), (4, '유출/사칭/사기'), (5, '낚시/놀람/도배'), (6, '정당/정치인 비하 및 선거운동')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInfoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lecture.examinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lecture.lectureevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '게시판 성격에 부적절함'), (1, '욕설/비하'), (2, '음란물/불건전한 만남 및 대화'), (3, '상업적 광고 및 판매'), (4, '유출/사칭/사기'), (5, '낚시/놀람/도배'), (6, '정당/정치인 비하 및 선거운동')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comment.comment')),
            ],
        ),
    ]
