# Generated by Django 3.2.6 on 2022-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.SmallIntegerField(null=True)),
                ('first_half', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonym_enabled', models.BooleanField(blank=True, default=True)),
                ('is_market', models.BooleanField(blank=True, default=False)),
                ('title_enabled', models.BooleanField(blank=True, default=True)),
                ('question_enabled', models.BooleanField(blank=True, default=False)),
                ('notice_enabled', models.BooleanField(blank=True, default=False)),
                ('board_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HotBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
