# Generated by Django 3.2.6 on 2021-12-05 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='anonym_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='is_market',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='notice_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='question_enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='title_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
