# Generated by Django 3.2.6 on 2021-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211205_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.IntegerField(default=1),
        ),
    ]
