# Generated by Django 3.2.6 on 2022-01-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='head_board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_boards', to='board.board'),
        ),
    ]
