# Generated by Django 3.2.6 on 2022-01-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_bestboard_hotboard'),
        ('board', '0004_board_head_board'),
    ]

    operations = [
    ]
