# Generated by Django 3.2.6 on 2022-01-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('num_of_likes', models.PositiveIntegerField(blank=True, default=0)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('head_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tail_comments', to='comment.comment')),
            ],
        ),
    ]
