# Generated by Django 3.2.6 on 2022-01-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
