# Generated by Django 3.2.6 on 2022-01-22 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0003_remove_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reporting_users',
            field=models.ManyToManyField(related_name='comment_reporting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
