# Generated by Django 3.2.6 on 2022-01-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_like_users'),
        ('comment', '0004_alter_comment_is_anonymous'),
    ]

    operations = [
    ]
