# Generated by Django 3.2.6 on 2022-01-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_reporting_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='head_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tail_comments', to='comment.comment'),
        ),
    ]
