# Generated by Django 3.2.6 on 2022-01-16 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0003_delete_timetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('private', models.CharField(choices=[('전체공개', '전채공개'), ('친구공개', '친구공개'), ('비공개', '비공개')], default='전체공개', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ManyToManyField(null=True, to='lecture.Lecture')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
