# Generated by Django 3.2.6 on 2022-01-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_delete_timetable'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='lecture',
            field=models.ManyToManyField(blank=True, to='lecture.Lecture'),
        ),
    ]
