# Generated by Django 3.2.6 on 2021-12-01 08:33

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile/default.png', upload_to=user.models.profile_upload_func),
        ),
    ]
