# Generated by Django 3.2.6 on 2021-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
