# Generated by Django 3.2.6 on 2022-01-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_socialaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='social_id',
            field=models.CharField(max_length=100),
        ),
    ]
