# Generated by Django 3.2.6 on 2022-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_socialaccount_social_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_nickname_update',
            field=models.DateField(default=None, null=True),
        ),
    ]
