# Generated by Django 3.2.6 on 2022-01-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_userpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='anonymous_num',
        ),
        migrations.AddField(
            model_name='userpost',
            name='anonymous_nickname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
