# Generated by Django 3.2.6 on 2022-01-22 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20220111_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reporting_users',
            field=models.ManyToManyField(related_name='reporting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
