# Generated by Django 3.2.6 on 2022-01-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211221_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymous_comment_num',
            field=models.IntegerField(default=1),
        ),
    ]
