# Generated by Django 3.2.6 on 2022-01-22 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_post_reporting_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reporting_users',
            field=models.ManyToManyField(related_name='post_reporting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
