# Generated by Django 3.2.6 on 2022-01-13 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('instructor', models.CharField(blank=True, max_length=50)),
                ('self_made', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=3)),
                ('degree', models.CharField(max_length=5)),
                ('grade', models.SmallIntegerField(null=True)),
                ('course_code', models.CharField(max_length=15)),
                ('lecture_code', models.IntegerField()),
                ('credits', models.SmallIntegerField()),
                ('lecture', models.SmallIntegerField()),
                ('laboratory', models.SmallIntegerField()),
                ('type', models.CharField(blank=True, max_length=30)),
                ('cart', models.IntegerField()),
                ('quota', models.IntegerField()),
                ('remark', models.TextField(null=True)),
                ('language', models.CharField(max_length=4)),
                ('self_made', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('2022년 1학기', '2022년 1학기'), ('2021년 겨울학기', '2021년 겨울학기'), ('2021년 2학기', '2021년 2학기'), ('2021년 여름학기', '2021년 여름학기'), ('2021년 1학기', '2021년 1학기'), ('2020년 겨울학기', '2020년 겨울학기'), ('2020년 2학기', '2020년 2학기'), ('2020년 여름학기', '2020년 여름학기'), ('2020년 1학기', '2020년 1학기')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('private', models.CharField(choices=[('전체공개', '전채공개'), ('친구공개', '친구공개'), ('비공개', '비공개')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ManyToManyField(null=True, to='lecture.Lecture')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
                ('point', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토')], max_length=1)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=30)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='LectureEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.SmallIntegerField(choices=[(2, '많음'), (1, '보통'), (0, '없음')], default=1)),
                ('team_project', models.SmallIntegerField(choices=[(2, '많음'), (1, '보통'), (0, '없음')], default=1)),
                ('grade', models.SmallIntegerField(choices=[(2, '너그러움'), (1, '보통'), (0, '깐깐함')], default=2)),
                ('attendance', models.SmallIntegerField(choices=[(4, '혼용'), (3, '직접호명'), (2, '지정좌석'), (1, '전자출결'), (0, '반영안함')], default=3)),
                ('exam', models.SmallIntegerField(choices=[(4, '네번이상'), (3, '세번'), (2, '두번'), (1, '한번'), (0, '없음')], default=2)),
                ('rating', models.SmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=3)),
                ('semester', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('num_of_likes', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.course')),
                ('like_users', models.ManyToManyField(related_name='like_evaluations', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.semester'),
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.SmallIntegerField(choices=[(0, '중간고사'), (1, '기말고사'), (2, '1차'), (3, '2차'), (4, '3차'), (5, '4차'), (6, '기타')], default=0)),
                ('semester', models.CharField(max_length=10)),
                ('strategy', models.TextField()),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[(0, '객관식'), (1, '주관식'), (2, 'T/F형'), (3, '약술형'), (4, '논술형'), (5, '구술'), (6, '기타')], max_length=13, null=True)),
                ('examples', models.TextField()),
                ('num_of_likes', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.course')),
                ('like_users', models.ManyToManyField(related_name='like_exam_info', to=settings.AUTH_USER_MODEL)),
                ('readable_users', models.ManyToManyField(related_name='readable_evaluations', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.college')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecture.department'),
        ),
    ]
