# Generated by Django 3.2.6 on 2022-01-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
