# Generated by Django 3.2.6 on 2022-01-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='language',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='type',
        ),
    ]
