# Generated by Django 3.2.6 on 2022-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20220114_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='exam',
            field=models.SmallIntegerField(choices=[(0, '중간고사'), (1, '기말고사'), (2, '1차'), (3, '2차'), (4, '3차'), (5, '4차'), (6, '기타')]),
        ),
        migrations.AlterField(
            model_name='lectureevaluation',
            name='assignment',
            field=models.SmallIntegerField(choices=[(2, '많음'), (1, '보통'), (0, '없음')]),
        ),
        migrations.AlterField(
            model_name='lectureevaluation',
            name='attendance',
            field=models.SmallIntegerField(choices=[(4, '혼용'), (3, '직접호명'), (2, '지정좌석'), (1, '전자출결'), (0, '반영안함')]),
        ),
        migrations.AlterField(
            model_name='lectureevaluation',
            name='exam',
            field=models.SmallIntegerField(choices=[(4, '네번이상'), (3, '세번'), (2, '두번'), (1, '한번'), (0, '없음')]),
        ),
        migrations.AlterField(
            model_name='lectureevaluation',
            name='grade',
            field=models.SmallIntegerField(choices=[(2, '너그러움'), (1, '보통'), (0, '깐깐함')]),
        ),
        migrations.AlterField(
            model_name='lectureevaluation',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')]),
        ),
        migrations.AlterField(
            model_name='lectureevaluation',
            name='team_project',
            field=models.SmallIntegerField(choices=[(2, '많음'), (1, '보통'), (0, '없음')]),
        ),
    ]
