# Generated by Django 3.2.6 on 2022-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_examtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='examinfo',
            name='types',
            field=models.ManyToManyField(to='lecture.ExamType'),
        ),
    ]
