# Generated by Django 3.2.6 on 2022-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20220118_0023'),
        ('lecture', '0003_delete_timetable'),
        ('lecture', '0006_auto_20220117_1826'),
    ]

    operations = [
    ]
