# Generated by Django 3.2.6 on 2022-01-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_merge_20220119_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='self_made',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
