# Generated by Django 3.2.6 on 2022-01-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_auto_20220120_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
