# Generated by Django 3.2.6 on 2022-01-22 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0009_alter_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinfo',
            name='reporting_users',
            field=models.ManyToManyField(related_name='exam_info_reporting_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lectureevaluation',
            name='reporting_users',
            field=models.ManyToManyField(related_name='eval_reporting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
